In [29]:
import pandas as pd
import zipfile
import os

In [30]:
zip_path = "archive.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("shopping_data")

print("ZIP file extracted successfully!")

ZIP file extracted successfully!

In [31]:
os.listdir("shopping_data")

['backpacks.csv',
 'bath-robe.csv',
 'bath-towels.csv',
 'bathroom-accessories.csv',
 'bedsheets.csv',
 'belts.csv',
 'bodysuit.csv',
 'boots.csv',
 'boxers.csv',
 'bra.csv',
 'bracelet.csv',
 'briefs.csv',
 'camisoles.csv',
 'candle-holders.csv',
 'caps.csv',
 'casual-shoes.csv',
 'chair-cover.csv',
 'clothing-set.csv',
 'clutches.csv',
 'co-ords.csv',
 'Combined_dataset.csv',
 'curtains-and-sheers.csv',
 'cutlery.csv',
 'dinnerware.csv',
 'dresses.csv',
 'duffel-bag.csv',
 'dungarees.csv',
 'dupatta.csv',
 'earrings.csv',
 'ethnic-dresses.csv',
 'face-moisturisers.csv',
 'face-wash-and-cleanser.csv',
 'flats.csv',
 'flip-flops.csv',
 'floor-mats--dhurries.csv',
 'formal-shoes.csv',
 'foundation.csv',
 'gloves.csv',
 'hair-accessory.csv',
 'hair-brush-and-comb.csv',
 'hair-cream-and-mask.csv',
 'hair-masks.csv',
 'handbags.csv',
 'headphones.csv',
 'heels.csv',
 'home-fragrance-set.csv',
 'innerwear-vests.csv',
 'jackets.csv',
 'jeans.csv',
 'jumpsuit.csv',
 'kurta-sets.csv',
 'kurtas.csv',
 'kurtis.csv',
 'lipstick.csv',
 'lounge-pants.csv',
 'lounge-shorts.csv',
 'lounge-tshirts.csv',
 'mangalsutra.csv',
 'mobile-accessories.csv',
 'night-suits.csv',
 'nightdress.csv',
 'outdoor-masks.csv',
 'palazzos.csv',
 'perfume-and-body-mist.csv',
 'pillow-covers.csv',
 'README.md',
 'ring.csv',
 'runners.csv',
 'sandals.csv',
 'saree-blouse.csv',
 'sarees.csv',
 'scarves.csv',
 'shampoo-and-conditioner.csv',
 'shaving-essentials.csv',
 'sherwani.csv',
 'shirts.csv',
 'shorts.csv',
 'showpieces.csv',
 'skirts.csv',
 'sports-shoes.csv',
 'sunglasses.csv',
 'sweaters.csv',
 'sweatshirts.csv',
 'swim-tops.csv',
 'table-covers.csv',
 'thermal-bottoms.csv',
 'tights.csv',
 'tops.csv',
 'towel-set.csv',
 'track-pants.csv',
 'trolley-bag.csv',
 'trousers.csv',
 'trunk.csv',
 'tshirts.csv',
 'tunics.csv',
 'wall-art.csv',
 'wallets.csv',
 'watches.csv',
 'yoga-mats.csv']

In [32]:
df = pd.read_csv("shopping_data/Combined_dataset.csv")

In [33]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [34]:
df.shape

(1000, 24)

In [35]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [36]:
print("Data Types:")
print(df.dtypes)

Data Types:
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [38]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [39]:
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [40]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

Missing Values in Each Column:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [41]:
missing_percent = (df.isnull().sum() / len(df)) * 100

print(missing_percent)

product_id                 0.0
title                      0.0
product_description        0.0
rating                     0.0
ratings_count              0.0
initial_price              0.0
discount                  12.1
final_price                0.0
currency                   0.0
images                     0.0
delivery_options           0.0
product_details            0.0
breadcrumbs                0.0
product_specifications     0.0
amount_of_stars            0.0
what_customers_said       57.3
seller_name               30.1
sizes                      0.0
videos                    78.1
seller_information        30.1
variations                56.2
best_offer                 0.0
more_offers                0.0
category                   0.0
dtype: float64

In [42]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [43]:
cat_cols = df.select_dtypes(include=['object', 'string']).columns

for col in cat_cols:
    if not df[col].mode().empty:
        df[col] = df[col].fillna(df[col].mode()[0])

In [44]:
print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [45]:
df.drop_duplicates(inplace=True)

print("Duplicates Removed Successfully")

Duplicates Removed Successfully

In [46]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [47]:
df[['title', 'category', 'initial_price', 'rating']].head()

            title   category  initial_price  rating
0     Lino Perros  backpacks           3995     3.8
1  Tommy Hilfiger  backpacks           2899     4.5
2           Lavie  backpacks           2999     4.4
3          F Gear  backpacks           1675     4.4
4       MYTRIDENT  bath-robe           2899     4.7

In [48]:
high_rated = df[df['rating'] > 4]

high_rated[['title', 'rating']].head(10)

             title  rating
1   Tommy Hilfiger     4.5
2            Lavie     4.4
3           F Gear     4.4
4        MYTRIDENT     4.7
5              H&M     4.5
7          My Room     4.7
8          My Room     4.5
10       MYTRIDENT     4.4
15    Home Ecstasy     4.5
17          Arrabi     4.3

In [49]:
import numpy as np

df['quantity'] = np.random.randint(1, 5, len(df))

df['total_amount'] = df['initial_price'] * df['quantity']

df[['initial_price', 'quantity', 'total_amount']].head()

   initial_price  quantity  total_amount
0           3995         2          7990
1           2899         3          8697
2           2999         2          5998
3           1675         4          6700
4           2899         2          5798

In [50]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,7990
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,Sup███om ███,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,3,8697
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,Sup███om ███,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,5998
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,Sup███om ███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,4,6700
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,Sup███om ███,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,2,5798

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                1000 non-null   float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     1000 non-null   str
 16  seller_name             1000 non-null   str
 17  sizes                   1000 non-null   str
 18  videos                  1000 non-null   str
 19  seller_information      1000 non-null   str
 20  variations              1000 non-null   str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
 24  quantity                1000 non-null   int32
 25  total_amount            1000 non-null   int64
dtypes: float64(2), int32(1), int64(4), str(19)
memory usage: 199.3 KB

In [53]:
df.to_csv("Cleaned_Shopping_Dataset.csv", index=False)

print("Cleaned_Shopping_Dataset saved successfully.")

Cleaned_Shopping_Dataset saved successfully.

In [54]:
import os

for file in os.listdir():
    if "Cleaned" in file:
        print(file)

Cleaned_Shopping_Dataset.csv

In [55]:
import os

print(os.path.abspath("Cleaned_Shopping_Dataset.csv"))

C:\Users\sahil nichit\Week_1 Celebal_Assignment\Cleaned_Shopping_Dataset.csv

In [28]:
# Summary

1. Loaded the shopping dataset using Pandas.
2. Explored the dataset using head(), shape(), columns, and info().
3. Identified and handled missing values using median and mode.
4. Removed duplicate records from the dataset.
5. Performed filtering and column selection operations.
6. Created a derived column (discount_amount/total_amount).
7. Saved the cleaned dataset as Cleaned_Shopping_Dataset.csv.

Conclusion:
The dataset was successfully cleaned and prepared for further analysis.

SyntaxError: invalid syntax (4060792465.py, line 3)